---
- hosts: webservers 
  become: True
  tasks:
    - name: Update cache
      yum:
        update_only: yes
    - name: Install packages
      yum:
        name: "httpd"
        state: "present"
    # To use with Container.    
    # - name: Start Apache server
      # service:
        # name: httpd
        # state: started
        # enabled: True
    - name: Start Apache server with command line
      command: /usr/sbin/apachectl -k start    
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
